export const Alumni_data=[
    
    {"Name": "Mandeep",
        "image":"Mandeep.jpg",        
},
    {"Name": "Mukul",
        "image":"Mukul.jpeg",        
},
    {"Name": "Aseem",
        "image":"Aseem.jpeg",        
},
    {"Name": "Akash",
        "image":"Akash.png",        
},
    {"Name": "Sarthak",
        "image":"Sarthak.jpeg",        
},
    {"Name": "Saumyadeep",
        "image":"Saumyadeep.jpg",        
},
    {"Name": "Dhruv",
        "image":"Dhruv.jpg",        
},
    {"Name": "Devesh",
        "image":"Devesh.jpeg",        
},
    {"Name": "Suraj",
        "image":"Suraj.jpg",        
},
    {"Name": "Aniket",
        "image":"Aniket.jpeg",        
},
    {"Name": "Pulkit",
        "image":"Pulkit.jpg",        
},
    {"Name": "Lokinder",
        "image":"Lokinder.jpeg",        
},
    {"Name": "Neel",
        "image":"Neel.jpg",        
},
    {"Name": "Rishin",
        "image":"Rishin.jpeg",        
}
    
]